image: node:18

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
    - node_modules/

variables:
  PNPM_CACHE_FOLDER: .pnpm-store

stages:
  - setup
  - code_quality
  - build
  - test
  - release

before_script:
  - npm install -g pnpm
  - pnpm config set store-dir .pnpm-store

install:
  stage: setup
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint:
  stage: code_quality
  script:
    - pnpm run lint
  dependencies:
    - install
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

typecheck:
  stage: code_quality
  script:
    - pnpm run type-check
  dependencies:
    - install
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
    - pnpm run build-only
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  dependencies:
    - install
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    # Crée le fichier release avec la version du package.json
    - version=$(node -p "require('./package.json').version")
    - |
      cat > release_notes.md << EOF
      # Release v${version}
      ## Changes
      - See commit history for changes
      ## Installation
      1. Copy the content of dist/c-helper-codex.cjs to your common.js page
      EOF
    # Copie le fichier build dans les assets de la release
    - cp dist/c-helper-codex.cjs "c-helper-v${version}.user.js"
  artifacts:
    paths:
      - release_notes.md
      - "c-helper-v${version}.user.js"
  release:
    name: 'Release v${version}'
    description: './release_notes.md'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'c-helper-v${version}.user.js'
          url: '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/c-helper-v${version}.user.js'
  rules:
    - if: $CI_COMMIT_TAG